[package]
name = "launcher"
version = "1.3.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
rustc_version_runtime = "0.3.0"

[profile.release]
strip = "symbols"
lto = "fat"
panic = "abort"
codegen-units = 1
